# Form implementation generated from reading ui file 'dialogopenchart.ui'
#
# Created by: PyQt6 UI code generator 6.6.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_DialogOpenChart(object):
    def setupUi(self, DialogOpenChart):
        DialogOpenChart.setObjectName("DialogOpenChart")
        DialogOpenChart.resize(700, 540)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(DialogOpenChart.sizePolicy().hasHeightForWidth())
        DialogOpenChart.setSizePolicy(sizePolicy)
        DialogOpenChart.setMaximumSize(QtCore.QSize(700, 540))
        DialogOpenChart.setMinimumSize(QtCore.QSize(700, 540))
        self.label_picture = QtWidgets.QLabel(parent=DialogOpenChart)
        self.label_picture.setGeometry(QtCore.QRect(10, 10, 671, 491))
        self.label_picture.setText("")
        self.label_picture.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_picture.setObjectName("label_picture")
        self.button_close = QtWidgets.QPushButton(parent=DialogOpenChart)
        self.button_close.setGeometry(QtCore.QRect(610, 510, 80, 18))
        self.button_close.setObjectName("button_close")

        self.retranslateUi(DialogOpenChart)
        QtCore.QMetaObject.connectSlotsByName(DialogOpenChart)

        self.button_close.clicked.connect(DialogOpenChart.close)

    def retranslateUi(self, DialogOpenChart):
        _translate = QtCore.QCoreApplication.translate
        DialogOpenChart.setWindowTitle(_translate("DialogOpenChart", "Dialog"))
        self.button_close.setText(_translate("DialogOpenChart", "Close"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DialogOpenChart = QtWidgets.QDialog()
    ui = Ui_DialogOpenChart()
    ui.setupUi(DialogOpenChart)
    DialogOpenChart.show()
    sys.exit(app.exec())
